<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_LazyLoad
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>

<?php use Magento\Framework\App\Action\Action;

$image_url=$block->getViewFileUrl('images/loader-2.gif');
$unique_slider_key = $block->getUniqueSliderKey();
$np_slider_id="mavenbird-new-slider-".$unique_slider_key;
$np_content_id="cwsNewProducts-".$unique_slider_key;
?>
<?php if (($_products = $block->getProductCollection()) && $_products->getSize()): ?>
    <div class="cwsNew" id="<?= $escaper->escapeHtmlAttr($np_content_id);?>">
        <div id="np_scroll_loading" style="display:none;"><img src="<?= $escaper->escapeUrl($image_url); ?>" alt="Loading..." /></div>
        <?php if ($block->getShowHeading()): ?>
            <div class="title"><h3><?= $escaper->escapeHtml($block->getHeading()) ?></h3></div>
        <?php endif; ?>
        <?php
            $_products = $block->getProductCollection();
            $_helper = $block->getOutputHelper();
        ?>
        <?php
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    
            /*** Position for actions regarding image size changing in vde if needed */
            $pos = $block->getPositioned();
            $position = '';
        if ($pos != null) {
            $position = ' style="left:'.$block->getVar("{$image}:width").'px;'.' top:'.$block->getVar("{$image}:height").'px;"';
        }
        ?>
        <?php if ($block->getShowSlider()): ?>
            <div id="cwsNpSlider" class="mage-new-slider <?= $escaper->escapeHtmlAttr($viewMode) ?> products wrapper <?= $escaper->escapeHtmlAttr($viewMode) ?> products-<?= $escaper->escapeHtmlAttr($viewMode) ?>">
        <?php else:?>
            <!-- auto load new -->
            <div class="<?php if (!$block->getAjaxscrollPage()): ?> auto_load_new <?php endif; ?>products wrapper <?= $escaper->escapeHtmlAttr($viewMode) ?> products-<?= $escaper->escapeHtmlAttr($viewMode) ?> grid<?= $escaper->escapeHtmlAttr($block->getProductsPerRow()) ?>">
        <?php endif; ?>
            <ol class="products list items product-items">
                <?php
                    $iterator = 1;
                    $i=0;?>
                <?php if ($block->getShowSlider()): ?>
                    <div class="owl-carousel" id="<?= $escaper->escapeHtmlAttr($np_slider_id); ?>">
                <?php endif; ?>
                <?php foreach ($_products as $_product):?>
                    <?= ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info" data-container="product-grid">
                        <?php // Product Image   ?>
                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
                    <span style="width:240px;" class="product-image-container">
                        <span style="padding-bottom: 137%;" class="product-image-wrapper">
                            <?php
                            $imageUrl = $block->getImageData()
                                    ->init($_product, $image)
                                    ->keepAspectRatio(true)
                                    ->keepFrame(false)
                                    ->resize(270, 371)
                                    ->getUrl();
                            ?>
                            <img class="product-image-photo" src="<?= $escaper->escapeUrl($imageUrl); ?>" />
                        </span>
                    </span>
                </a>
                        <div class="product details product-item-details">
                             <div style="padding: 0 2px;"><?= $block->getProductDetailsHtml($_product); ?></div>
                            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <strong class="product name product-item-name"> <a class="product-item-link" href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"><?= $escaper->escapeHtml($_helper->productAttribute($_product, $_product->getName(), 'name')) ?></a></strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            <?php if ($block->getProductsPrice()): ?>
                                <?= $escaper->escapeHtml($block->getProductPrice($_product)) ?>
                            <?php endif; ?>
                            <div class="product-item-inner">
                                
                                <div class="product actions product-item-actions"<?= $escaper->escapeHtmlAttr(($pos && strpos($pos, $viewMode . '-actions')) ? $position : '') ?>>
                                
                                    <?php if ($block->getAddToCart()): ?>
                                        <div class="actions-primary"<?= $escaper->escapeHtmlAttr(($pos && strpos($pos, $viewMode . '-primary')) ? $position : ''); ?>>
                                    <?php endif; ?>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?= $escaper->escapeUrl($postParams['action']); ?>" method="post" data-mage-init='{"validation":{}}'>
                                            <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr($postParams['data']['product']); ?>">
                                            <input type="hidden" name="<?= $escaper->escapeHtmlAttr(\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED) ?>"
                                                                                           value="<?= $escaper->escapeHtmlAttr($postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED]) ?>">
                                             <?= $block->getBlockHtml('formkey')?>
                                            <?php if (($_product->isSaleable()) && ($block->getAddToCart())): ?>
                                                <button type="submit" title="<?= $escaper->escapeHtml(__('Add to Cart')) ?>" class="action tocart primary"> <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span> </button>
                                            <?php endif; ?>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ($block->getAddToCart()): ?>
                                        </div>
                                    <?php endif; ?>
                                    
                                        <?php if ($block->getAddToWishlist() || $block->getAddToCompare()): ?>
                                        <div data-role="add-to-links" class="actions-secondary"<?= $escaper->escapeHtmlAttr(($pos && strpos($pos, $viewMode . '-secondary')) ? $position : ''); ?>>
                                            <?php if ($block->getAddToWishlist()): ?>
                                                <?php if ($block->getDataHelper()->isAllow()): ?>
                                                    <a href="#" class="action towishlist" title="<?= $escaper->escapeHtmlAttr(__('Add to Wishlist')) ?>" aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wishlist')) ?>" data-post='<?= $escaper->escapeHtmlAttr($block->getAddToWishlistParams($_product)) ?>' data-action="add-to-wishlist" role="button"><span><?= $escaper->escapeHtml(__('Add to Wishlist')) ?></span></a>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompare()): ?>
                                                <?php $compareHelper = $block->getCompareHelper(); ?>
                                                <a href="#" class="action tocompare" title="<?= $escaper->escapeHtml(__('Add to Compare')); ?>" aria-label="<?= $escaper->escapeHtml(__('Add to Compare')); ?>" data-post='<?= $escaper->escapeHtmlAttr($compareHelper->getPostDataParams($_product)); ?>' role="button"><span><?= $escaper->escapeHtml(__('Add to Compare')) ?></span></a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                <?php if (!$block->getShowSlider()): ?>
                                    <?php if ($block->getDescription()):?>
                                        <div class="product description product-item-description">
                                            <?= $escaper->escapeHtml($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')) ?>
                                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>" title="<?= $escaper->escapeHtmlAttr($_productNameStripped) ?>" class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        </div>
                    <?= ($iterator == count($_products)+1) ? '</li>' : '' ?>
                <?php  endforeach; ?>
                    <?php if ($block->getShowSlider()) { ?>
                    </div>
                <?php } ?>
            </ol>
        </div>
         <?php if (!$block->getShowSlider()): ?>
        <div class="mageNewToolbar toolbar bottom"> <?= $block->getPagerHtml();  ?></div>
    <?php endif; ?>
        
        <?php if ($block->getShowSlider()): ?>
            <?php $navigation = $block->getNavarrow() == '1' ? 'true' : 'false';
            $autoplay=$block->getAutoscroll()=='1' ? 'true':'false';
            $slider_id=$np_slider_id;
            $dots=$block->getDots()=='1' ? 'true':'false';
            ?>
            <?php else: ?>
                <?php
                $navigation="";
                $autoplay="";
                $slider_id="";
                $dots="";
                ?>    
            <?php endif; ?>    
            <script>
            requirejs([
                'jquery',
                'mavenbirdNewProduct'                
            ], function ($) {
                var np_content_id="<?= $escaper->escapeJs($np_content_id); ?>";
                var product_count="<?= $escaper->escapeJs($_products->count());?>";
                var widget = $('#'+np_content_id).mavenbirdNewProduct({
                    "nav":"<?= $escaper->escapeJs($navigation); ?>",    
                    "product_count":product_count,
                    "autoplay":"<?= $escaper->escapeJs($autoplay); ?>",
                    "slider_id":"<?= $escaper->escapeJs($slider_id); ?>",
                    "dots":"<?= $escaper->escapeJs($dots); ?>"
                });                        
            });    
            </script>
    <!--</div>-->
    </div>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
       <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
